/**
 * The in-game half of the source of truth, written out so it can be checked against the
 * game's own controls screen.
 *
 * A profile sends keys; their effect depends on bindings held inside the game. This
 * renders, per game, every action the profiles use, the key it assumes, and the unit and
 * position that sends it, so the two halves can be compared directly.
 */

import { SLOTS } from "../types/azeron.js";
import type { ActionSpec, KeySlotSpec, RawSlotSpec } from "../types/profile.js";
import { iterBindings, ROLE_TAGS } from "./lint.js";
import type { ActionSet, Profile } from "./model-core.js";

export interface BindingRow {
  action: string;
  label: string;
  /** What the keypad sends, written the way the game's controls screen shows it. */
  key: string;
  tags: string[];
  /** unit:position entries, in the order the profiles were given. */
  sentFrom: string[];
  note: string | undefined;
}

export interface BindingSheet {
  game: string;
  rows: BindingRow[];
  /** Actions the game needs that no profile sends. */
  unbound: BindingRow[];
  /** Keys the profiles send that no action declares -- usually an app-side edit. */
  undeclared: { key: string; sentFrom: string[] }[];
}

function keyOf(spec: ActionSpec): string {
  if (spec.provided_by) return `(${spec.provided_by})`;
  if (spec.mouse) return `mouse ${spec.mouse}`;
  const parts = [spec.meta, spec.key].filter((part): part is string => Boolean(part));
  return parts.join(" + ") || "(unbound in game)";
}

function role(spec: ActionSpec): string {
  const tags = new Set(spec.tags ?? []);
  return ROLE_TAGS.find((tag) => tags.has(tag)) ?? "other";
}

function rawKeyOf(raw: KeySlotSpec & RawSlotSpec): string | null {
  const mouse = raw.mouse;
  if (typeof mouse === "string") return `mouse ${mouse}`;
  const key = raw.key ?? raw.key_raw;
  const meta = raw.meta ?? raw.meta_raw;
  const parts = [meta, key].filter(
    (part): part is string => typeof part === "string" && part !== "0",
  );
  return parts.length > 0 ? parts.join(" + ") : null;
}

export function bindingSheet(
  gameName: string,
  actions: ActionSet,
  profiles: readonly Profile[],
): BindingSheet {
  const sentFrom = new Map<string, string[]>();
  const undeclared = new Map<string, string[]>();

  for (const profile of profiles) {
    const unit = profile.unit ?? profile.slug;
    for (const { position, slot, action, raw } of iterBindings(profile)) {
      const where = SLOTS.includes(slot as never)
        ? `${unit}:${position}`
        : `${unit}:${position}.${slot.replace("stick_", "")}`;
      if (action) {
        const list = sentFrom.get(action) ?? [];
        if (!list.includes(where)) list.push(where);
        sentFrom.set(action, list);
        continue;
      }
      if (!raw) continue;
      const key = rawKeyOf(raw);
      if (key === null) continue;
      const list = undeclared.get(key) ?? [];
      if (!list.includes(where)) list.push(where);
      undeclared.set(key, list);
    }
  }

  const all: BindingRow[] = Object.entries(actions.actions).map(([id, spec]) => ({
    action: id,
    label: spec.label ?? id,
    key: keyOf(spec),
    tags: spec.tags ?? [],
    sentFrom: sentFrom.get(id) ?? [],
    note: spec.note,
  }));

  const order = (row: BindingRow): number =>
    ROLE_TAGS.indexOf(role(actions.actions[row.action] ?? {}) as never);
  all.sort((a, b) => order(a) - order(b) || a.label.localeCompare(b.label));

  return {
    game: gameName,
    rows: all.filter((row) => row.sentFrom.length > 0),
    unbound: all.filter((row) => row.sentFrom.length === 0),
    undeclared: [...undeclared.entries()]
      .map(([key, from]) => ({ key, sentFrom: from }))
      .sort((a, b) => a.key.localeCompare(b.key)),
  };
}

export function renderBindingsMarkdown(sheet: BindingSheet): string {
  const lines: string[] = [
    `# ${sheet.game} -- in-game bindings`,
    "",
    "Generated by `azeron bindings`. Check each row against the game's controls screen.",
    "If a key here does not match the game, fix `actions.yaml` -- not the profile.",
    "",
    "| Action | Key in game | Sent from | Tags |",
    "| --- | --- | --- | --- |",
  ];
  for (const row of sheet.rows) {
    lines.push(
      `| ${row.label} | \`${row.key}\` | ${row.sentFrom.join(", ")} | ${row.tags.join(", ")} |`,
    );
  }

  if (sheet.unbound.length > 0) {
    lines.push("", "## Declared but not sent by any unit", "");
    for (const row of sheet.unbound) {
      lines.push(
        `- ${row.label} (\`${row.key}\`)${row.tags.includes("required") ? " — **required**" : ""}`,
      );
    }
  }

  if (sheet.undeclared.length > 0) {
    lines.push(
      "",
      "## Sent by a unit but not declared as an action",
      "",
      "Usually an edit made in the Azeron app. Add an action for each, or the key is",
      "doing something the repo cannot check.",
      "",
    );
    for (const entry of sheet.undeclared) {
      lines.push(`- \`${entry.key}\` from ${entry.sentFrom.join(", ")}`);
    }
  }

  return `${lines.join("\n")}\n`;
}

export function renderBindingsCsv(sheet: BindingSheet): string {
  const escape = (value: string): string => `"${value.replace(/"/g, '""')}"`;
  const lines = ["action,label,key_in_game,sent_from,tags,status"];
  const push = (row: BindingRow, status: string): void => {
    lines.push(
      [row.action, row.label, row.key, row.sentFrom.join(" "), row.tags.join(" "), status]
        .map(escape)
        .join(","),
    );
  };
  for (const row of sheet.rows) push(row, "sent");
  for (const row of sheet.unbound) push(row, row.tags.includes("required") ? "MISSING" : "unused");
  for (const entry of sheet.undeclared) {
    lines.push(
      [entry.key, entry.key, entry.key, entry.sentFrom.join(" "), "", "UNDECLARED"]
        .map(escape)
        .join(","),
    );
  }
  return `${lines.join("\n")}\n`;
}
