/**
 * Turn an Azeron export back into profile YAML.
 *
 * Profiles are also edited in the Azeron app, so an app export has to come home as a git
 * diff. Anything the YAML schema cannot express in canonical form is
 * kept as a `*_raw` value rather than being dropped or guessed at.
 */

import { Document, isPair, isScalar, visit } from "yaml";

import type { ExportDocument, InputRecord, Slot } from "../types/azeron.js";
import {
  DEFAULT_DOUBLE_DELAY,
  DEFAULT_FEATURE_DELAY,
  HOLD_FIELDS,
  SLOTS,
  SLOT_FIELDS,
  STICK_DIRECTIONS,
  STICK_MODES,
  STICK_MODE_CODES,
  TYPE_NONE,
} from "../types/azeron.js";
import type { ActionSpec, PositionSpec, ProfileData, ProfileMeta } from "../types/profile.js";
import { describeSlot, matchAction, resolveSlot } from "./binding.js";
import * as keys from "./keys.js";
import type { ActionSet, Device } from "./model-core.js";

export const DECOMPILE_HEADER = `# Generated by \`azeron decompile\` -- edit freely, it is the source of truth.
# Rebuild with \`npm run azeron -- build\`; \`npm run azeron -- roundtrip\` verifies it.
`;

function tokens(record: InputRecord, field: keyof InputRecord): string[] {
  return record[field] as string[];
}

function stickSpec(record: InputRecord, actions: ActionSet | null): PositionSpec {
  const spec: PositionSpec = {};
  const mode = STICK_MODES[String(record.types[0])];
  spec.mode = mode ?? "unknown";

  const directions: PositionSpec["directions"] = {};
  const left = record.analogSettings?.analogKeys.left;
  if (left) {
    for (const direction of STICK_DIRECTIONS) {
      const name = keys.analogToName(left[direction][0]);
      if (name === null) continue;
      const action = matchAction({ key: name }, actions?.actions ?? null, direction);
      directions[direction] = action ?? { key: name };
    }
  }
  if (Object.keys(directions).length > 0) spec.directions = directions;
  return spec;
}

function derivedTypes(
  spec: PositionSpec,
  actions: Record<string, ActionSpec> | null,
  isStick: boolean,
): string[] {
  if (isStick) {
    const head = spec.mode ? (STICK_MODE_CODES[spec.mode] ?? TYPE_NONE) : TYPE_NONE;
    return [head, TYPE_NONE, TYPE_NONE];
  }
  return SLOTS.map((slot: Slot) => resolveSlot(spec[slot], actions)[0]);
}

/** One export input record to a YAML spec (empty object when nothing is bound). */
export function decompilePosition(
  record: InputRecord,
  actions: ActionSet | null,
  isStick: boolean,
): PositionSpec {
  const spec: PositionSpec = {};
  if (record.label) spec.label = record.label;

  if (isStick) {
    Object.assign(spec, stickSpec(record, actions));
  } else {
    SLOTS.forEach((slot: Slot, index: number) => {
      const [keyField, metaField] = SLOT_FIELDS[slot];
      const typeCode = String(record.types[index]);
      const described = describeSlot(
        typeCode,
        String(tokens(record, keyField)[0]),
        String(tokens(record, metaField)[0]),
      );
      if (!described.spec) return;
      const action = matchAction(described.spec, actions?.actions ?? null, record.label);
      spec[slot] = action ?? described.spec;
    });
  }

  if (record.featureDelay !== DEFAULT_FEATURE_DELAY) {
    spec.feature_delay = record.featureDelay;
  }
  if (record.doubleDelay !== DEFAULT_DOUBLE_DELAY) {
    spec.double_delay = record.doubleDelay;
  }
  for (const slot of SLOTS) {
    if (record[HOLD_FIELDS[slot]]) {
      if (slot === "tap") spec.hold = true;
      else if (slot === "long") spec.hold_long = true;
      else spec.hold_double = true;
    }
  }

  // Preserve type codes we cannot derive (the unexplained "6" and "0" slots).
  if (Object.keys(spec).length > 0) {
    const derived = derivedTypes(spec, actions?.actions ?? null, isStick);
    const actual = record.types.map(String);
    if (derived.join("|") !== actual.join("|")) spec.raw = { types: actual };
  }
  return spec;
}

export interface DecompileOptions {
  actions?: ActionSet | null;
  profileIndex?: number;
  meta?: Partial<ProfileMeta>;
}

export function decompile(
  exported: ExportDocument,
  device: Device,
  options: DecompileOptions = {},
): ProfileData {
  const index = options.profileIndex ?? 0;
  const source = exported.profiles[index];
  if (!source) throw new Error(`export has no profile at index ${String(index)}`);

  const byPin = new Map<number, InputRecord>();
  for (const record of source.inputs) {
    if (!byPin.has(record.pinOne)) byPin.set(record.pinOne, record);
  }

  const positions: Record<string, PositionSpec> = {};
  for (const [name, position] of Object.entries(device.positions)) {
    if (device.unknownPins.has(position.pin)) continue;
    const record = byPin.get(position.pin);
    if (!record) continue;
    const spec = decompilePosition(record, options.actions ?? null, device.isStick(name));
    if (Object.keys(spec).length > 0) positions[name] = spec;
  }

  const meta: ProfileMeta = {
    id: source.id,
    name: source.name,
    device: device.name,
    ...(device.hand ? { unit: device.hand } : {}),
    ...options.meta,
  };
  return { profile: meta, positions };
}

/** Emit profile YAML with the tight little mappings kept on one line. */
const FLOW_UNDER = new Set<string>(["raw", "directions", ...SLOTS, ...STICK_DIRECTIONS]);

function parentKeyName(path: readonly unknown[]): string | null {
  const parent = path[path.length - 1];
  if (parent && isPair(parent) && isScalar(parent.key)) return String(parent.key.value);
  return null;
}

export function dumpProfile(data: ProfileData, header = DECOMPILE_HEADER): string {
  const doc = new Document(data);
  visit(doc, {
    Map(_key, node, path) {
      const name = parentKeyName(path);
      if (name !== null && FLOW_UNDER.has(name)) node.flow = true;
    },
    Seq(_key, node, path) {
      if (parentKeyName(path) === "types") node.flow = true;
    },
  });
  const body = doc.toString({
    lineWidth: 100,
    defaultStringType: "PLAIN",
    defaultKeyType: "PLAIN",
  });
  return header ? header + body : body;
}
